# Site settings
title: Protein Computer
description: > # this means to ignore newlines until "baseurl:"
    does not compute
baseurl: "" # the subpath of your site, e.g. /blog/
url: "tasilb.me" # the base hostname & protocol for your site
twitter_username: tasilb
github_username:  tasilb

# Blog settings
paginate: 5
paginate_path: "/blog/:num/"

# Build settings
markdown: kramdown

# Gems
gems: [jekyll-paginate]
